[package]
name = "pg_fake_sqlx"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
bigdecimal = "0.4"
chrono = { version = "0.4", default-features = false, features = ["std"] }
either = "1"
futures-core = "0.3"
futures-util = "0.3"
hashlink = "0.11"
log = "0.4"
pg_fake = { path = "../pg_fake" }
sqlx = { version = "0.9", default-features = false, features = ["bigdecimal", "runtime-tokio"] }
sqlx-core = { version = "0.9", features = ["bigdecimal"] }
tokio = { version = "1", features = ["rt", "sync"] }
url = "2"
uuid = "1"

[dev-dependencies]
chaos_theory = "0.3.5"
dotenvy = "0.15"
sqlx-postgres = "0.9"
testcontainers = { version = "0.27", features = ["blocking"] }
testcontainers-modules = { version = "0.15", features = ["blocking", "postgres"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "time"] }
