[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"

[workspace.lints.clippy]
too_many_arguments = "allow"

[patch.crates-io]
sqlparser = { git = "https://github.com/myxo/datafusion-sqlparser-rs", rev = "26eeb2114037b79220f1eaa8a82171271b7aee77" }
