[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"

[workspace.lints.clippy]
too_many_arguments = "allow"

[patch.crates-io]
sqlparser = { git = "https://github.com/myxo/datafusion-sqlparser-rs", rev = "a5131269ef597512d2afee9cc8799474426c9923" }
