[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"

[workspace.lints.clippy]
too_many_arguments = "allow"

[patch.crates-io]
sqlparser = { git = "https://github.com/myxo/datafusion-sqlparser-rs", rev = "1bcc091c6b9a49df73e2ed9348f85471a33a985e" }
