use pg_fake::{
    api::Db,
    error::SqlState,
    value::{BaseType, Value},
};

#[test]
fn creates_serial_columns_with_owned_sequences() {
    let db = Db::create();
    let mut session = db.create_session();
    session
        .execute("CREATE TABLE serial_rows (small smallserial, normal serial, big bigserial)")
        .unwrap();

    let result = session
        .query(
            "INSERT INTO serial_rows DEFAULT VALUES RETURNING small, normal, big",
            &[],
        )
        .unwrap();
    assert_eq!(
        result.rows,
        vec![vec![Value::Int2(1), Value::Int4(1), Value::Int8(1)]]
    );
    assert_eq!(
        result
            .columns
            .iter()
            .map(|column| column.type_oid)
            .collect::<Vec<_>>(),
        vec![
            BaseType::Int2.map_to_oid(),
            BaseType::Int4.map_to_oid(),
            BaseType::Int8.map_to_oid(),
        ]
    );
    assert_eq!(
        session
            .query(
                "SELECT pg_get_serial_sequence('serial_rows', 'normal')",
                &[]
            )
            .unwrap()
            .rows,
        vec![vec![Value::Text("public.serial_rows_normal_seq".into())]]
    );

    session.execute("DROP TABLE serial_rows").unwrap();
    assert_eq!(
        session
            .query("SELECT nextval('serial_rows_normal_seq')", &[])
            .unwrap_err()
            .sqlstate,
        SqlState::UndefinedTable
    );
}

#[test]
fn prevents_directly_dropping_owned_sequences() {
    let db = Db::create();
    let mut session = db.create_session();
    session
        .execute("CREATE TABLE owned_sequence_rows (id integer)")
        .unwrap();
    session
        .execute("CREATE SEQUENCE owned_sequence OWNED BY owned_sequence_rows.id")
        .unwrap();

    assert_eq!(
        session
            .execute("DROP SEQUENCE owned_sequence")
            .unwrap_err()
            .sqlstate,
        SqlState::DependentObjectsStillExist
    );
    session.execute("DROP TABLE owned_sequence_rows").unwrap();
    assert_eq!(
        session
            .query("SELECT nextval('owned_sequence')", &[])
            .unwrap_err()
            .sqlstate,
        SqlState::UndefinedTable
    );
}

#[test]
fn quotes_owned_sequence_names_and_preserves_literal_column_case() {
    let db = Db::create();
    let mut session = db.create_session();
    session
        .execute("CREATE TABLE public.\"Mixed\" (\"ID\" SERIAL)")
        .unwrap();

    let sequence = session
        .query(
            "SELECT pg_get_serial_sequence('public.\"Mixed\"', 'ID')",
            &[],
        )
        .unwrap();
    assert_eq!(
        sequence.rows,
        vec![vec![Value::Text("public.\"Mixed_ID_seq\"".into())]]
    );
    let Value::Text(sequence) = &sequence.rows[0][0] else {
        panic!("serial lookup must return text");
    };
    assert_eq!(
        session
            .query(&format!("SELECT nextval('{sequence}')"), &[])
            .unwrap()
            .rows,
        vec![vec![Value::Int8(1)]]
    );

    session
        .execute(
            "CREATE TABLE keyword_owner (id INTEGER); \
             CREATE SEQUENCE public.\"select\" OWNED BY keyword_owner.id",
        )
        .unwrap();
    let keyword_sequence = session
        .query(
            "SELECT pg_get_serial_sequence('public.keyword_owner', 'id')",
            &[],
        )
        .unwrap();
    assert_eq!(
        keyword_sequence.rows,
        vec![vec![Value::Text("public.\"select\"".into())]]
    );
    let Value::Text(keyword_sequence) = &keyword_sequence.rows[0][0] else {
        panic!("serial lookup must return text");
    };
    assert_eq!(
        session
            .query(&format!("SELECT nextval('{keyword_sequence}')"), &[])
            .unwrap()
            .rows,
        vec![vec![Value::Int8(1)]]
    );

    session
        .execute(
            "CREATE TABLE value_owner (id INTEGER); \
             CREATE SEQUENCE public.value OWNED BY value_owner.id",
        )
        .unwrap();
    assert_eq!(
        session
            .query(
                "SELECT pg_get_serial_sequence('public.value_owner', 'id')",
                &[],
            )
            .unwrap()
            .rows,
        vec![vec![Value::Text("public.value".into())]]
    );
}

#[test]
fn generates_identity_values_and_handles_explicit_by_default_values() {
    let db = Db::create();
    let mut session = db.create_session();
    session
        .execute(
            "CREATE TABLE identity_rows (always_id integer GENERATED ALWAYS AS IDENTITY (START WITH 10), default_id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 20))",
        )
        .unwrap();

    assert_eq!(
        session
            .query(
                "INSERT INTO identity_rows DEFAULT VALUES RETURNING always_id, default_id",
                &[],
            )
            .unwrap()
            .rows,
        vec![vec![Value::Int4(10), Value::Int8(20)]]
    );
    assert_eq!(
        session
            .execute("INSERT INTO identity_rows (always_id) VALUES (1)")
            .unwrap_err()
            .sqlstate,
        SqlState::GeneratedAlways
    );
    session
        .execute("INSERT INTO identity_rows (default_id) VALUES (99)")
        .unwrap();
    assert_eq!(
        session
            .query(
                "INSERT INTO identity_rows DEFAULT VALUES RETURNING always_id, default_id",
                &[],
            )
            .unwrap()
            .rows,
        vec![vec![Value::Int4(12), Value::Int8(22)]]
    );
}

#[test]
fn rejects_non_integer_identity_columns() {
    let db = Db::create();
    let mut session = db.create_session();

    assert_eq!(
        session
            .execute("CREATE TABLE invalid_identity (id text GENERATED ALWAYS AS IDENTITY)")
            .unwrap_err()
            .sqlstate,
        SqlState::DatatypeMismatch
    );
}

#[test]
fn restores_owned_sequences_with_implicit_batch_ddl_rollback() {
    let db = Db::create();
    let mut session = db.create_session();

    assert_eq!(
        session
            .execute("CREATE TABLE transient_serial (id serial); SELECT 1 / 0")
            .unwrap_err()
            .sqlstate,
        SqlState::DivisionByZero
    );
    assert_eq!(
        session
            .query("SELECT nextval('transient_serial_id_seq')", &[])
            .unwrap_err()
            .sqlstate,
        SqlState::UndefinedTable
    );

    session
        .execute("CREATE TABLE restored_serial (id serial)")
        .unwrap();
    assert_eq!(
        session
            .query("SELECT nextval('restored_serial_id_seq')", &[])
            .unwrap()
            .rows,
        vec![vec![Value::Int8(1)]]
    );
    assert_eq!(
        session
            .execute("DROP TABLE restored_serial; SELECT 1 / 0")
            .unwrap_err()
            .sqlstate,
        SqlState::DivisionByZero
    );
    assert_eq!(
        session
            .query("SELECT nextval('restored_serial_id_seq')", &[])
            .unwrap()
            .rows,
        vec![vec![Value::Int8(2)]]
    );
}
